allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  msgpackr-extract: set this to true or false
  prisma: false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
